var hierarchy =
[
    [ "cdocx::AbstractNumberingDefinition", "structcdocx_1_1AbstractNumberingDefinition.html", null ],
    [ "cdocx::BookmarkReplacer::BatchResult", "structcdocx_1_1BookmarkReplacer_1_1BatchResult.html", null ],
    [ "cdocx::Bookmark", "classcdocx_1_1Bookmark.html", null ],
    [ "cdocx::BookmarkCollection", "classcdocx_1_1BookmarkCollection.html", null ],
    [ "cdocx::BookmarkFormat", "structcdocx_1_1BookmarkFormat.html", null ],
    [ "cdocx::BookmarkInserter", "classcdocx_1_1BookmarkInserter.html", null ],
    [ "cdocx::BookmarkNameCache", "classcdocx_1_1BookmarkNameCache.html", null ],
    [ "cdocx::BookmarkReplacer", "classcdocx_1_1BookmarkReplacer.html", null ],
    [ "cdocx::Border", "classcdocx_1_1Border.html", null ],
    [ "cdocx::ParagraphProperties::Border", "structcdocx_1_1ParagraphProperties_1_1Border.html", null ],
    [ "cdocx::BorderParseMapping", "structcdocx_1_1BorderParseMapping.html", null ],
    [ "cdocx::Borders", "classcdocx_1_1Borders.html", null ],
    [ "cdocx::ParagraphProperties::Borders", "structcdocx_1_1ParagraphProperties_1_1Borders.html", null ],
    [ "cdocx::BorderSerializeMapping", "structcdocx_1_1BorderSerializeMapping.html", null ],
    [ "cdocx::BorderTypeMapping", "structcdocx_1_1BorderTypeMapping.html", null ],
    [ "cdocx::BreakTypeMapping", "structcdocx_1_1BreakTypeMapping.html", null ],
    [ "cdocx::CaptionFormat", "structcdocx_1_1CaptionFormat.html", null ],
    [ "cdocx::CaptionGenerator", "classcdocx_1_1CaptionGenerator.html", null ],
    [ "cdocx::CDocx", "classcdocx_1_1CDocx.html", null ],
    [ "cdocx::CellCollection", "classcdocx_1_1CellCollection.html", null ],
    [ "cdocx::CellFormat", "classcdocx_1_1CellFormat.html", null ],
    [ "cdocx::TableProperties::CellMargin", "structcdocx_1_1TableProperties_1_1CellMargin.html", null ],
    [ "cdocx::CellMerge", "structcdocx_1_1CellMerge.html", null ],
    [ "cdocx::CellVerticalAlignmentMapping", "structcdocx_1_1CellVerticalAlignmentMapping.html", null ],
    [ "cdocx::Color", "classcdocx_1_1Color.html", null ],
    [ "cdocx::SectionProperties::Columns", "structcdocx_1_1SectionProperties_1_1Columns.html", null ],
    [ "cdocx::CommentCollection", "classcdocx_1_1CommentCollection.html", null ],
    [ "cdocx::ContentType", "structcdocx_1_1ContentType.html", null ],
    [ "cdocx::ControlChar", "classcdocx_1_1ControlChar.html", null ],
    [ "cdocx::ConvertUtil", "classcdocx_1_1ConvertUtil.html", null ],
    [ "cdocx::DocumentBuilder", "classcdocx_1_1DocumentBuilder.html", null ],
    [ "cdocx::DocumentInserter", "classcdocx_1_1DocumentInserter.html", null ],
    [ "cdocx::DocumentProperties", "classcdocx_1_1DocumentProperties.html", null ],
    [ "cdocx::DocumentSearch", "classcdocx_1_1DocumentSearch.html", null ],
    [ "cdocx::DocumentVisitor", "classcdocx_1_1DocumentVisitor.html", null ],
    [ "cdocx::DocxTree", "classcdocx_1_1DocxTree.html", null ],
    [ "cdocx::DropCapPositionMapping", "structcdocx_1_1DropCapPositionMapping.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "cdocx::DocxTreeNode", "structcdocx_1_1DocxTreeNode.html", null ],
      [ "cdocx::Node", "classcdocx_1_1Node.html", [
        [ "cdocx::BookmarkEnd", "classcdocx_1_1BookmarkEnd.html", null ],
        [ "cdocx::BookmarkStart", "classcdocx_1_1BookmarkStart.html", null ],
        [ "cdocx::CommentRangeEnd", "classcdocx_1_1CommentRangeEnd.html", null ],
        [ "cdocx::CommentRangeStart", "classcdocx_1_1CommentRangeStart.html", null ],
        [ "cdocx::CompositeNode", "classcdocx_1_1CompositeNode.html", [
          [ "cdocx::Body", "classcdocx_1_1Body.html", null ],
          [ "cdocx::Cell", "classcdocx_1_1Cell.html", null ],
          [ "cdocx::Comment", "classcdocx_1_1Comment.html", null ],
          [ "cdocx::Document", "classcdocx_1_1Document.html", null ],
          [ "cdocx::Footnote", "classcdocx_1_1Footnote.html", null ],
          [ "cdocx::HeaderFooter", "classcdocx_1_1HeaderFooter.html", null ],
          [ "cdocx::Paragraph", "classcdocx_1_1Paragraph.html", null ],
          [ "cdocx::Row", "classcdocx_1_1Row.html", null ],
          [ "cdocx::Section", "classcdocx_1_1Section.html", null ],
          [ "cdocx::Table", "classcdocx_1_1Table.html", null ]
        ] ],
        [ "cdocx::EndnoteReference", "classcdocx_1_1EndnoteReference.html", null ],
        [ "cdocx::FootnoteReference", "classcdocx_1_1FootnoteReference.html", null ],
        [ "cdocx::FormField", "classcdocx_1_1FormField.html", null ],
        [ "cdocx::Inline", "classcdocx_1_1Inline.html", [
          [ "cdocx::Field", "classcdocx_1_1Field.html", [
            [ "cdocx::Hyperlink", "classcdocx_1_1Hyperlink.html", null ]
          ] ],
          [ "cdocx::Run", "classcdocx_1_1Run.html", null ],
          [ "cdocx::SpecialChar", "classcdocx_1_1SpecialChar.html", null ]
        ] ]
      ] ],
      [ "cdocx::Style", "classcdocx_1_1Style.html", null ]
    ] ],
    [ "cdocx::EndnoteCollection", "classcdocx_1_1EndnoteCollection.html", null ],
    [ "cdocx::FileFormatInfo", "classcdocx_1_1FileFormatInfo.html", null ],
    [ "cdocx::FileFormatUtil", "classcdocx_1_1FileFormatUtil.html", null ],
    [ "cdocx::Font", "classcdocx_1_1Font.html", null ],
    [ "cdocx::TextProperties::Font", "structcdocx_1_1TextProperties_1_1Font.html", null ],
    [ "cdocx::TextProperties::FontStyle", "structcdocx_1_1TextProperties_1_1FontStyle.html", null ],
    [ "cdocx::FootnoteCollection", "classcdocx_1_1FootnoteCollection.html", null ],
    [ "cdocx::FormatMapping", "structcdocx_1_1FormatMapping.html", null ],
    [ "cdocx::HeaderFooterCollection", "classcdocx_1_1HeaderFooterCollection.html", null ],
    [ "cdocx::HeaderFooterRef", "structcdocx_1_1HeaderFooterRef.html", null ],
    [ "cdocx::HeaderFooterTypeMapping", "structcdocx_1_1HeaderFooterTypeMapping.html", null ],
    [ "cdocx::HighlightMapping", "structcdocx_1_1HighlightMapping.html", null ],
    [ "cdocx::ImageFormatInfo", "structcdocx_1_1ImageFormatInfo.html", null ],
    [ "cdocx::ImageSize", "structcdocx_1_1ImageSize.html", null ],
    [ "cdocx::ImageWatermarkOptions", "structcdocx_1_1ImageWatermarkOptions.html", null ],
    [ "cdocx::ParagraphProperties::Indentation::Indent", "structcdocx_1_1ParagraphProperties_1_1Indentation_1_1Indent.html", null ],
    [ "cdocx::ParagraphProperties::Indentation", "structcdocx_1_1ParagraphProperties_1_1Indentation.html", null ],
    [ "cdocx::Iterator< T, P, C >", "classcdocx_1_1Iterator.html", null ],
    [ "cdocx::IteratorHelper", "classcdocx_1_1IteratorHelper.html", null ],
    [ "cdocx::LevelDefinition::LevelFont", "structcdocx_1_1LevelDefinition_1_1LevelFont.html", null ],
    [ "cdocx::ParagraphProperties::Spacing::LineSpacing", "structcdocx_1_1ParagraphProperties_1_1Spacing_1_1LineSpacing.html", null ],
    [ "cdocx::LineSpacingRuleMapping", "structcdocx_1_1LineSpacingRuleMapping.html", null ],
    [ "cdocx::ListFormat", "structcdocx_1_1ListFormat.html", null ],
    [ "cdocx::LoadConfig", "structcdocx_1_1LoadConfig.html", null ],
    [ "cdocx::LoadError", "structcdocx_1_1LoadError.html", null ],
    [ "cdocx::LoadResult", "structcdocx_1_1LoadResult.html", null ],
    [ "cdocx::LoadStatistics", "structcdocx_1_1LoadStatistics.html", null ],
    [ "cdocx::MailMerge", "classcdocx_1_1MailMerge.html", null ],
    [ "cdocx::NodeCollection", "classcdocx_1_1NodeCollection.html", null ],
    [ "cdocx::NumberingDefinition", "structcdocx_1_1NumberingDefinition.html", null ],
    [ "cdocx::NumberingManager", "classcdocx_1_1NumberingManager.html", null ],
    [ "cdocx::NumberStyleMapping", "structcdocx_1_1NumberStyleMapping.html", null ],
    [ "cdocx::OrientationMapping", "structcdocx_1_1OrientationMapping.html", null ],
    [ "cdocx::SectionProperties::PageMargins", "structcdocx_1_1SectionProperties_1_1PageMargins.html", null ],
    [ "cdocx::PageSetup", "classcdocx_1_1PageSetup.html", null ],
    [ "cdocx::SectionProperties::PageSize", "structcdocx_1_1SectionProperties_1_1PageSize.html", null ],
    [ "cdocx::ParagraphAlignmentMapping", "structcdocx_1_1ParagraphAlignmentMapping.html", null ],
    [ "cdocx::ParagraphBuilder", "classcdocx_1_1ParagraphBuilder.html", null ],
    [ "cdocx::ParagraphCollection", "classcdocx_1_1ParagraphCollection.html", null ],
    [ "cdocx::ParagraphFormat", "classcdocx_1_1ParagraphFormat.html", null ],
    [ "cdocx::ParagraphProperties", "structcdocx_1_1ParagraphProperties.html", [
      [ "cdocx::LevelDefinition", "structcdocx_1_1LevelDefinition.html", null ]
    ] ],
    [ "cdocx::ParagraphProperties::Spacing::ParaSpacing", "structcdocx_1_1ParagraphProperties_1_1Spacing_1_1ParaSpacing.html", null ],
    [ "cdocx::TextProperties::Position", "structcdocx_1_1TextProperties_1_1Position.html", null ],
    [ "cdocx::PpAlignmentMapping", "structcdocx_1_1PpAlignmentMapping.html", null ],
    [ "cdocx::Range", "classcdocx_1_1Range.html", null ],
    [ "cdocx::Relationship", "structcdocx_1_1Relationship.html", null ],
    [ "cdocx::ReplacementStats", "structcdocx_1_1ReplacementStats.html", null ],
    [ "cdocx::TemplateEngine::Result", "structcdocx_1_1TemplateEngine_1_1Result.html", null ],
    [ "cdocx::RowCollection", "classcdocx_1_1RowCollection.html", null ],
    [ "cdocx::RowFormat", "classcdocx_1_1RowFormat.html", null ],
    [ "cdocx::RunCollection", "classcdocx_1_1RunCollection.html", null ],
    [ "cdocx::ScriptTypeMapping", "structcdocx_1_1ScriptTypeMapping.html", null ],
    [ "cdocx::SectionCollection", "classcdocx_1_1SectionCollection.html", null ],
    [ "cdocx::SectionProperties", "structcdocx_1_1SectionProperties.html", null ],
    [ "cdocx::SectionRange", "structcdocx_1_1SectionRange.html", null ],
    [ "cdocx::TemplateEngine::Setter", "classcdocx_1_1TemplateEngine_1_1Setter.html", null ],
    [ "cdocx::Shading", "classcdocx_1_1Shading.html", null ],
    [ "cdocx::ParagraphProperties::Spacing", "structcdocx_1_1ParagraphProperties_1_1Spacing.html", null ],
    [ "cdocx::TextProperties::Spacing", "structcdocx_1_1TextProperties_1_1Spacing.html", null ],
    [ "cdocx::ParagraphProperties::Indentation::Special", "structcdocx_1_1ParagraphProperties_1_1Indentation_1_1Special.html", null ],
    [ "cdocx::SpecialCharMapping", "structcdocx_1_1SpecialCharMapping.html", null ],
    [ "cdocx::StyleCollection", "classcdocx_1_1StyleCollection.html", null ],
    [ "cdocx::StyleTypeMapping", "structcdocx_1_1StyleTypeMapping.html", null ],
    [ "cdocx::TableAlignmentMapping", "structcdocx_1_1TableAlignmentMapping.html", null ],
    [ "cdocx::TableBorders", "structcdocx_1_1TableBorders.html", null ],
    [ "cdocx::TableBuilder", "classcdocx_1_1TableBuilder.html", null ],
    [ "cdocx::TableCell", "classcdocx_1_1TableCell.html", null ],
    [ "cdocx::TableCollection", "classcdocx_1_1TableCollection.html", null ],
    [ "cdocx::TableFormat", "classcdocx_1_1TableFormat.html", null ],
    [ "cdocx::TableOperations", "classcdocx_1_1TableOperations.html", null ],
    [ "cdocx::TableProperties", "structcdocx_1_1TableProperties.html", null ],
    [ "cdocx::TableRow", "classcdocx_1_1TableRow.html", null ],
    [ "cdocx::TabStop", "structcdocx_1_1TabStop.html", null ],
    [ "cdocx::TabStopCollection", "classcdocx_1_1TabStopCollection.html", null ],
    [ "cdocx::Template", "classcdocx_1_1Template.html", null ],
    [ "cdocx::TemplateEngine", "classcdocx_1_1TemplateEngine.html", null ],
    [ "cdocx::TemplateFormat", "classcdocx_1_1TemplateFormat.html", null ],
    [ "cdocx::TemplateValue", "classcdocx_1_1TemplateValue.html", null ],
    [ "cdocx::TextFormatContext", "classcdocx_1_1TextFormatContext.html", null ],
    [ "cdocx::TextFormFieldTypeMapping", "structcdocx_1_1TextFormFieldTypeMapping.html", null ],
    [ "cdocx::TextProperties", "structcdocx_1_1TextProperties.html", [
      [ "cdocx::LevelDefinition", "structcdocx_1_1LevelDefinition.html", null ]
    ] ],
    [ "cdocx::TextWatermarkOptions", "structcdocx_1_1TextWatermarkOptions.html", null ],
    [ "cdocx::TextProperties::Underline", "structcdocx_1_1TextProperties_1_1Underline.html", null ],
    [ "cdocx::UnderlineTypeMapping", "structcdocx_1_1UnderlineTypeMapping.html", null ],
    [ "cdocx::Watermark", "classcdocx_1_1Watermark.html", null ],
    [ "cdocx::TableProperties::Width", "structcdocx_1_1TableProperties_1_1Width.html", null ],
    [ "cdocx::XmlEscapeMapping", "structcdocx_1_1XmlEscapeMapping.html", null ]
];