var searchData=
[
  ['batchresult_0',['BatchResult',['../structcdocx_1_1BookmarkReplacer_1_1BatchResult.html',1,'cdocx::BookmarkReplacer']]],
  ['body_1',['Body',['../classcdocx_1_1Body.html',1,'cdocx']]],
  ['bookmark_2',['Bookmark',['../classcdocx_1_1Bookmark.html',1,'cdocx']]],
  ['bookmarkcollection_3',['BookmarkCollection',['../classcdocx_1_1BookmarkCollection.html',1,'cdocx']]],
  ['bookmarkend_4',['BookmarkEnd',['../classcdocx_1_1BookmarkEnd.html',1,'cdocx']]],
  ['bookmarkformat_5',['BookmarkFormat',['../structcdocx_1_1BookmarkFormat.html',1,'cdocx']]],
  ['bookmarkinserter_6',['BookmarkInserter',['../classcdocx_1_1BookmarkInserter.html',1,'cdocx']]],
  ['bookmarknamecache_7',['BookmarkNameCache',['../classcdocx_1_1BookmarkNameCache.html',1,'cdocx']]],
  ['bookmarkreplacer_8',['BookmarkReplacer',['../classcdocx_1_1BookmarkReplacer.html',1,'cdocx']]],
  ['bookmarkstart_9',['BookmarkStart',['../classcdocx_1_1BookmarkStart.html',1,'cdocx']]],
  ['border_10',['border',['../classcdocx_1_1Border.html',1,'cdocx::Border'],['../structcdocx_1_1ParagraphProperties_1_1Border.html',1,'cdocx::ParagraphProperties::Border']]],
  ['borderparsemapping_11',['BorderParseMapping',['../structcdocx_1_1BorderParseMapping.html',1,'cdocx']]],
  ['borders_12',['borders',['../classcdocx_1_1Borders.html',1,'cdocx::Borders'],['../structcdocx_1_1ParagraphProperties_1_1Borders.html',1,'cdocx::ParagraphProperties::Borders']]],
  ['borderserializemapping_13',['BorderSerializeMapping',['../structcdocx_1_1BorderSerializeMapping.html',1,'cdocx']]],
  ['bordertypemapping_14',['BorderTypeMapping',['../structcdocx_1_1BorderTypeMapping.html',1,'cdocx']]],
  ['breaktypemapping_15',['BreakTypeMapping',['../structcdocx_1_1BreakTypeMapping.html',1,'cdocx']]]
];
